@MiniApiServer_Api_HostAddress = http://localhost:5269

POST {{MiniApiServer_Api_HostAddress}}/api/data-in
Content-Type: application/json
Accept: application/json

{
  "description": "first test input",
  "dataA": 10,
  "dataB": 4
}

###
