// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniApiServer.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniApiServer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MiniApiServerDbContext))]
    [Migration("20260319150617_HardenStateCoordinator")]
    partial class HardenStateCoordinator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniApiServer.Domain.Entities.DataIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DataA")
                        .HasColumnType("integer")
                        .HasColumnName("data_a");

                    b.Property<int>("DataB")
                        .HasColumnType("integer")
                        .HasColumnName("data_b");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("created_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("data_in", (string)null);
                });

            modelBuilder.Entity("MiniApiServer.Domain.Entities.DataSubtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataInId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_in_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<DateTime>("created_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DataInId")
                        .IsUnique();

                    b.ToTable("data_subtractions", (string)null);
                });

            modelBuilder.Entity("MiniApiServer.Domain.Entities.DataSumm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataInId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_in_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<DateTime>("created_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DataInId")
                        .IsUnique();

                    b.ToTable("data_summs", (string)null);
                });

            modelBuilder.Entity("MiniApiServer.Domain.Entities.Stat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("NumberOfOperations")
                        .HasColumnType("integer")
                        .HasColumnName("n_of_operations");

                    b.Property<int>("TotalOfSubtractions")
                        .HasColumnType("integer")
                        .HasColumnName("total_of_subtractions");

                    b.Property<int>("TotalOfSums")
                        .HasColumnType("integer")
                        .HasColumnName("total_of_sums");

                    b.HasKey("Id");

                    b.ToTable("stats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
